name: Alerta Crypto SQL
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install sqlite3

      - name: Run Analysis
        run: node monitor.js

      - name: Save Database Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add crypto_history.db
          git commit -m "Update DB [skip ci]" || echo "No changes"
          git push
